[package]
name = "map-macro"
version = "0.2.0"
authors = ["jofas <jonas@fc-web.de>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "Declarative map! and set! macros for statically initializing a HashMap or HashSet (like the vec! macro for Vec)"
keyword = ["macro", "HashMap", "HashSet", "map", "set"]
homepage = "https://github.com/jofas/map_macro"
repository = "https://github.com/jofas/map_macro"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
